// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtoCommerce.BModule.Data.Repositories;

namespace VirtoCommerce.BModule.Data.Migrations
{
    [DbContext(typeof(BDbContext))]
    partial class BDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VirtoCommerce.AModule.Data.Model.SeamlessEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Numeric")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Seamless");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SeamlessEntity");
                });

            modelBuilder.Entity("VirtoCommerce.BModule.Data.Model.SeamlessEntity2", b =>
                {
                    b.HasBaseType("VirtoCommerce.AModule.Data.Model.SeamlessEntity");

                    b.Property<string>("NewField")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("SeamlessEntity2");
                });
#pragma warning restore 612, 618
        }
    }
}
