// <auto-generated />
namespace MemberExtensionSampleModule.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MemberDbContext2_12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberDbContext2_12));
        
        string IMigrationMetadata.Id
        {
            get { return "201608310943556_MemberDbContext2_12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
