// <auto-generated />
namespace External.PricingModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPricelistEx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPricelistEx));
        
        string IMigrationMetadata.Id
        {
            get { return "201906141137543_AddPricelistEx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
