// <auto-generated />
namespace CartModule2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cart_TaxPercentRate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cart_TaxPercentRate));
        
        string IMigrationMetadata.Id
        {
            get { return "201704241528105_Cart_TaxPercentRate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
